[package]
name = "migration"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[[bin]]
name = "migrate"
path = "src/main.rs"

[dependencies]
async-trait = "0.1"
clap = { version = "4.3", features = ["derive", "env"] }
dotenvy = "0.15"
sea-orm-cli = { version = "1.1", default-features = false, features = ["cli"] }
sea-orm-migration = { version = "1.1", features = ["runtime-tokio-rustls", "sqlx-postgres"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
