[package]
name = "links_tool"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
vercel_runtime = { version = "2", features = ["axum"] }
tokio = { version = "1", features = ["full"] }
axum = { version = "0.8" }
tower = { version = "0.5" }
tower-http = { version = "0.6", features = ["cors"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
dotenvy = "0.15"
argon2 = "0.5"
jsonwebtoken = "9"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4"] }
rand = "0.8"
sha2 = "0.10"
hex = "0.4"
sea-orm = { version = "1.1", default-features = false, features = [
    "macros",
    "runtime-tokio-rustls",
    "sqlx-postgres",
    "with-chrono",
] }
sea-query = { version = "0.32", default-features = false, features = [
    "backend-postgres",
    "derive",
] }
sqlx = { version = "0.8", default-features = false, features = [
    "macros",
    "postgres",
    "runtime-tokio-rustls",
] }
utoipa = { version = "5", features = ["axum_extras", "macros"] }
utoipa-axum = "0.2"

[dev-dependencies]
colored = "3"
serde_json = "1"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "vercel"
path = "api/vercel.rs"

[[bin]]
name = "gen-openapi"
path = "src/bin/gen_openapi.rs"

[workspace]
members = ["migration"]
resolver = "3"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
